# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaRacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('fase', models.CharField(choices=[('inicial', 'Inicial'), ('crescimento', 'Crescimento'), ('terminacao', 'Terminação'), ('postura', 'Postura'), ('reproducao', 'Reprodução')], max_length=20)),
                ('ingredientes', models.TextField(help_text='Lista de ingredientes e proporções')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fórmula de Ração',
                'verbose_name_plural': 'Fórmulas de Ração',
                'ordering': ['nome'],
            },
        ),
    ]
