# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('racao', 'Ração'), ('graos', 'Grãos/Ingredientes'), ('vacina', 'Vacina'), ('medicamento', 'Medicamento'), ('material', 'Material'), ('outros', 'Outros')], max_length=20)),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validade', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
