# Generated by Django 6.0.3 on 2026-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='estoque'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='estoque'),
        ),
    ]
