# Generated by Django 6.0.3 on 2026-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_itemestoque_anexo_movimentoestoque_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='ultimo_preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('consumo', 'Consumo'), ('descarte', 'Descarte/Perda'), ('ajuste', 'Ajuste'), ('uso_sanitario', 'Uso sanitário'), ('uso_lote', 'Uso em lote')], default='compra', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='unidade',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('un', 'un'), ('ml', 'ml'), ('l', 'L'), ('ovos', 'ovos')], default='un', max_length=20),
        ),
    ]
