# Generated by Django 6.0.3 on 2026-03-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aves', '0002_initial'),
        ('lotes', '0002_initial'),
        ('sanidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacaovacina',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacaovacina',
            name='ave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinas', to='aves.ave'),
        ),
        migrations.AddField(
            model_name='aplicacaovacina',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacaovacina',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacinas', to='lotes.lote'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='ave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos', to='aves.ave'),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos', to='lotes.lote'),
        ),
        migrations.AddField(
            model_name='tratamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamentos', to='sanidade.medicamento'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacina',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacaovacina',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='sanidade.vacina'),
        ),
    ]
