# Generated by Django 6.0.3 on 2026-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidade', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='receita_anexo',
            field=models.FileField(blank=True, null=True, upload_to='sanidade'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='receita_anexo',
            field=models.FileField(blank=True, null=True, upload_to='sanidade'),
        ),
    ]
