# Generated by Django 6.0.3 on 2026-04-03 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_alter_lote_linhagem_principal_and_more'),
        ('sanidade', '0003_tratamento_receita_anexo_vacina_receita_anexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacinaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_vacina', models.CharField(max_length=100)),
                ('data_prevista', models.DateField()),
                ('aplicada', models.BooleanField(default=False)),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_lote', to='lotes.lote')),
            ],
            options={
                'verbose_name': 'Vacina do Lote',
                'verbose_name_plural': 'Vacinas do Lote',
                'ordering': ['data_prevista'],
                'constraints': [models.UniqueConstraint(fields=('lote', 'nome_vacina', 'data_prevista'), name='unique_vacina_lote_data')],
            },
        ),
    ]
