# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incubacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('data_entrada', models.DateField()),
                ('tipo', models.CharField(choices=[('chocadeira', 'Chocadeira'), ('natural', 'Natural')], max_length=20)),
                ('quantidade_ovos', models.PositiveIntegerField()),
                ('origem_ovos', models.CharField(blank=True, max_length=100)),
                ('previsao_eclosao', models.DateField(blank=True, null=True)),
                ('data_eclosao', models.DateField(blank=True, null=True)),
                ('quantidade_nascida', models.PositiveIntegerField(default=0)),
                ('ovos_fertis', models.PositiveIntegerField(default=0)),
                ('ovos_infertis', models.PositiveIntegerField(default=0)),
                ('perdas', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Incubação',
                'verbose_name_plural': 'Incubações',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
