# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nascimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('quantidade_nascida', models.PositiveIntegerField()),
                ('quantidade_viva', models.PositiveIntegerField()),
                ('quantidade_morta', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nascimento',
                'verbose_name_plural': 'Nascimentos',
                'ordering': ['-data'],
            },
        ),
    ]
