# Generated by Django 6.0.3 on 2026-03-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aves', '0001_initial'),
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ovos', 'Ovos'), ('ave_viva', 'Ave viva'), ('ave_abatida', 'Ave abatida'), ('reprodutor', 'Reprodutor'), ('matriz', 'Matriz'), ('outros', 'Outros')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('status_pagamento', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('ave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='aves.ave')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='lotes.lote')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data'],
            },
        ),
    ]
