# Generated by Django 5.1.1 on 2026-04-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aves', '0005_ave_valor_referencia'),
        ('lotes', '0004_lote_reproducao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reprodutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz (Fêmea)'), ('reprodutor', 'Reprodutor (Macho)')], help_text='Matriz (fêmea) ou Reprodutor (macho)', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('descanso', 'Em descanso'), ('vendido', 'Vendido'), ('descartado', 'Descartado')], default='ativo', max_length=20)),
                ('qualidade_genetica', models.CharField(choices=[('padrao', 'Padrão'), ('superior', 'Superior'), ('pura', 'Pura/Linha')], default='padrao', max_length=20)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado para venda ou seguro', max_digits=10, null=True)),
                ('data_inicio_reproducao', models.DateField(blank=True, help_text='Data em que começou a participar de reproduções', null=True)),
                ('data_fim_reproducao', models.DateField(blank=True, help_text='Data em que foi retirado da reprodução (se aplicável)', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre performance genética, problemas, etc')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('ave', models.OneToOneField(help_text='Ave que será usada para reprodução', on_delete=django.db.models.deletion.CASCADE, related_name='reprodutor', to='aves.ave')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reprodutor',
                'verbose_name_plural': 'Reprodutores',
                'ordering': ['tipo', '-data_inicio_reproducao'],
            },
        ),
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(help_text='Data em que o casal começou a reproduzir')),
                ('data_fim', models.DateField(blank=True, help_text='Data em que o casal foi separado', null=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre o desempenho do casal')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, help_text='Lote onde o casal está alojado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotes.lote')),
                ('matriz_femea', models.ForeignKey(help_text='Matriz fêmea', limit_choices_to={'tipo': 'matriz'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casais_como_femea', to='reprodutores.reprodutor')),
                ('reprodutor_macho', models.ForeignKey(help_text='Reprodutor macho', limit_choices_to={'tipo': 'reprodutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casais_como_macho', to='reprodutores.reprodutor')),
            ],
            options={
                'verbose_name': 'Casal Reprodutor',
                'verbose_name_plural': 'Casais Reprodutores',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='reprodutor',
            index=models.Index(fields=['tipo', 'ativo'], name='repr_tipo_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='reprodutor',
            index=models.Index(fields=['status'], name='repr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='casal',
            index=models.Index(fields=['status', 'ativo'], name='casal_status_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='casal',
            index=models.Index(fields=['data_inicio'], name='casal_data_inicio_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casal',
            unique_together={('reprodutor_macho', 'matriz_femea', 'data_inicio')},
        ),
    ]
