# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('racao', 'Ração'), ('vacinas', 'Vacinas'), ('medicamentos', 'Medicamentos'), ('energia', 'Energia'), ('transporte', 'Transporte'), ('manutencao', 'Manutenção'), ('mao_obra', 'Mão de obra'), ('equipamentos', 'Equipamentos'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-data'],
            },
        ),
    ]
