# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_lancamentofinanceiro_comprovante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrcamentoFuturo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("valor_previsto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valor_ja_reservado", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejado",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[("baixa", "Baixa"), ("media", "Média"), ("alta", "Alta")],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("data_planejada", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="orcamentos")),
                ("ativo", models.BooleanField(default=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento Futuro",
                "verbose_name_plural": "Orçamentos Futuros",
                "ordering": ["-created_at"],
            },
        ),
    ]
