# Generated by Django 6.0.3 on 2026-04-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_orcamentofuturo"),
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="venda",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lancamento_financeiro",
                to="vendas.venda",
            ),
        ),
        migrations.AlterField(
            model_name="lancamentofinanceiro",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("racao", "Ração"),
                    ("vacinas", "Vacinas"),
                    ("medicamentos", "Medicamentos"),
                    ("energia", "Energia"),
                    ("transporte", "Transporte"),
                    ("manutencao", "Manutenção"),
                    ("mao_obra", "Mão de obra"),
                    ("equipamentos", "Equipamentos"),
                    ("vendas", "Venda"),
                    ("outros", "Outros"),
                ],
                max_length=20,
            ),
        ),
    ]
