# Generated by Django 6.0.3 on 2026-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoevento',
            name='acao',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('status', 'Status')], default='update', max_length=20),
        ),
        migrations.AddField(
            model_name='historicoevento',
            name='detalhes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
