# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('identificacao', models.CharField(blank=True, max_length=50, verbose_name='Identificação/Anilha')),
                ('nome', models.CharField(blank=True, max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('finalidade', models.CharField(choices=[('corte', 'Corte'), ('postura', 'Postura'), ('reproducao', 'Reprodução')], max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('viva', 'Viva'), ('vendida', 'Vendida'), ('morta', 'Morta'), ('abatida', 'Abatida')], default='viva', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ave',
                'verbose_name_plural': 'Aves',
                'ordering': ['codigo_interno'],
            },
        ),
    ]
