# Generated by Django 6.0.3 on 2026-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ave',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aves'),
        ),
    ]
