# Generated by Django 6.0.3 on 2026-03-29 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0003_ave_foto'),
        ('linhagens', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ave',
            name='linhagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aves', to='linhagens.linhagem'),
        ),
    ]
