# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aves", "0004_alter_ave_linhagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="ave",
            name="valor_referencia",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
