# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('data_criacao', models.DateField()),
                ('finalidade', models.CharField(choices=[('corte', 'Corte'), ('postura', 'Postura'), ('reproducao', 'Reprodução')], max_length=20)),
                ('quantidade_inicial', models.PositiveIntegerField()),
                ('quantidade_atual', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('local', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('custo_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumo_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
