# Generated by Django 6.0.3 on 2026-03-29 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhagens', '0002_initial'),
        ('lotes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='linhagem_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='linhagens.linhagem'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade_atual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
