# Generated by Django 6.0.3 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0003_alter_lote_linhagem_principal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="data_inicio_reproducao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="observacoes_reproducao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lote",
            name="quantidade_femeas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lote",
            name="quantidade_machos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lote",
            name="reprodutivo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lote",
            name="status_reprodutivo",
            field=models.CharField(
                blank=True,
                choices=[("ativo", "Ativo"), ("pausado", "Pausado"), ("encerrado", "Encerrado")],
                max_length=20,
            ),
        ),
    ]
