# Generated by Django 6.0.3 on 2026-03-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aves', '0002_initial'),
        ('genetica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrogenetico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrogenetico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrogenetico',
            name='filho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_genetico', to='aves.ave'),
        ),
        migrations.AddField(
            model_name='registrogenetico',
            name='mae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_mae', to='aves.ave'),
        ),
        migrations.AddField(
            model_name='registrogenetico',
            name='pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_pai', to='aves.ave'),
        ),
        migrations.AlterUniqueTogether(
            name='registrogenetico',
            unique_together={('pai', 'mae', 'filho')},
        ),
    ]
