# Generated by Django 6.0.3 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('quantidade_abatida', models.PositiveIntegerField()),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('custo_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receita_gerada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('destino', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Abate',
                'verbose_name_plural': 'Abates',
                'ordering': ['-data'],
            },
        ),
    ]
